// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeRPNw8RIBPLGkye4ItTKOsnrT2MafZhw',
    appId: '1:16556101827:web:e75732b51abe787b4e5276',
    messagingSenderId: '16556101827',
    projectId: 'spendwise-25648',
    authDomain: 'spendwise-25648.firebaseapp.com',
    storageBucket: 'spendwise-25648.firebasestorage.app',
    measurementId: 'G-KH21Z7ZRXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVmW5PtOo4a306sRK2zWJz9QZ-FFwIFVI',
    appId: '1:16556101827:android:80b002f4a56079264e5276',
    messagingSenderId: '16556101827',
    projectId: 'spendwise-25648',
    storageBucket: 'spendwise-25648.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Px8SKh6RDAtOgO9K6Sl8VX_Dtmtcd0I',
    appId: '1:16556101827:ios:6945dd9ad702c9054e5276',
    messagingSenderId: '16556101827',
    projectId: 'spendwise-25648',
    storageBucket: 'spendwise-25648.firebasestorage.app',
    iosBundleId: 'com.example.spendWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Px8SKh6RDAtOgO9K6Sl8VX_Dtmtcd0I',
    appId: '1:16556101827:ios:6945dd9ad702c9054e5276',
    messagingSenderId: '16556101827',
    projectId: 'spendwise-25648',
    storageBucket: 'spendwise-25648.firebasestorage.app',
    iosBundleId: 'com.example.spendWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeRPNw8RIBPLGkye4ItTKOsnrT2MafZhw',
    appId: '1:16556101827:web:7bb0f4c9d932a0344e5276',
    messagingSenderId: '16556101827',
    projectId: 'spendwise-25648',
    authDomain: 'spendwise-25648.firebaseapp.com',
    storageBucket: 'spendwise-25648.firebasestorage.app',
    measurementId: 'G-VG1P7GZB6R',
  );
}
